### PR TITLE
ecr: switch implementation to use the AWS SDK

### LINKED ISSUE #125: Amazon ECR Private login fails on Windows
#### Steps to reproduce this issue

1. Create a GitHub Action workflow using `windows-latest`
2. Try to use the `docker/login-action@v1` action to login to an Amazon ECR Private repository
3. Fail

#### Expected behaviour

Action should login with Amazon ECR Private.

#### Actual behaviour

Action fails with error: `Unable to locate executable file: C:\Program. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.`

Interestingly enough, using `aws-actions/amazon-ecr-login` works.

### Configuration

* Repository URL (if public): https://github.com/Vlaaaaaaad/bug-docker-login-windows
* Build URL (if public): https://github.com/Vlaaaaaaad/bug-docker-login-windows/runs/4571248514

```yml
name: App / Build and push

env:
  # In GitHub, go to Settings -> Secrets and set:
  #  AWS_ACCESS_KEY_ID to your own AWS Access Key ID, eg `AKIAIOSFODNN7EXAMPLE`
  #  AWS_SECRET_ACCESS_KEY to your own AWS Secret Access Key, eg `wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY`
  AWS_ECR_PRIVATE_ACCOUNT_ID: "355938773567"
  AWS_ECR_PRIVATE_REGION: "us-east-1"
  AWS_ECR_PRIVATE_REPO_NAME: "bug-docker-login-windows"

on:
  push:

jobs:
  windows:
    name: Amazon ECR Private - Windows
    runs-on: windows-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v2.4.0

      - name: Login to Amazon ECR Private - FAILS
        continue-on-error: true
        uses: docker/login-action@v1
        with:
          registry: ${{ env.AWS_ECR_PRIVATE_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_ECR_PRIVATE_REGION }}.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR - WORKS
        uses: aws-actions/amazon-ecr-login@v1.3.3
```
### Logs

[GitHub Action logs from the linked run](https://github.com/docker/login-action/files/7739968/logs_1.zip)

### PR DESCRIPTION
**Pull request by crazy-max**
Follow-up https://github.com/docker/login-action/pull/114#pullrequestreview-834026943
Fixes #125 

@Flydiverny Now using the AWS SDK so we don't need to rely on the AWS CLI.

With this we are also able to authenticate on Windows runners.

### CODE REVIEW

**Review by Flydiverny — COMMENTED** [review]
Nice!
I tested `docker/login-action@42ba9a1dc8ea3ab85b1c32bdcb2bff18ba03c94f` (before last force-push) on our self-hosted (linux) runner without providing any input credentials and it worked as expected for that use case 👍 

I was thinking maybe we could use the v3 aws-sdk lib instead of the v2 one, ie @aws-sdk/client-ecr and @aws-sdk/client-ecr-public. I tried to make these changes locally but for some reason `docker buildx bake validation` fails saying there's diffs to output. Seems to be `CRLF` vs `LF` issue 😅 
It seemed to reduce the dist size a bit since v3 sdk is modular.

**Comment by Flydiverny** [comment]
https://github.com/docker/login-action/pull/128 if you're curious

**Comment by aramalipoor** [comment]
FYI from ~1 hour when this PR is merged our pipelines started failing to login to AWS ECR, it could be related to the changes here.

image

**Comment by crazy-max** [comment]
@aramalipoor Can you add a comment with your workflow in #129 please?

**Pull request merged**
