### PR TITLE
update to node 16

### PR DESCRIPTION
**Pull request by crazy-max**
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by crazy-max** [comment]
@svasek While upgrading to node 16 I encounter an issue with the `proxy-agent` package. I switched to another module. Can you try with `uses: crazy-max/docker-login-action@node-16` and let me know if it still works? Thx.

**Comment by svasek** [comment]
> @svasek While upgrading to node 16 I encountered an issue with the `proxy-agent` package. I switched to another one. Can you try with `uses: crazy-max/docker-login-action@node-16` and let me know if it still works? Thx.

Hi 
Unfortunately it doesn't work:
```
Run github-test/docker-login-action@node-16
::save-state name=isPost::true
##[debug]Save intra-action state isPost = true
::save-state name=registry::***.dkr.ecr.us-west-2.amazonaws.com
##[debug]Save intra-action state registry = ***.dkr.ecr.us-west-2.amazonaws.com
::save-state name=logout::true
##[debug]Save intra-action state logout = true
Retrieving registries data through AWS SDK...
##[debug]Requesting AWS ECR auth token for ***
##[debug]Using http proxy http://proxy-us-aws.xxx.yyy:3128/
Error: A "socks" protocol must be specified! Got: http:
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Login to AWS ECR
```

**Comment by crazy-max** [comment]
@svasek Thanks for your feedback! That's what I thought. I will take a look and keep you in touch.

**Comment by crazy-max** [comment]
@svasek Can you try again? Thx!

**Comment by svasek** [comment]
Hi @crazy-max,
Looks good now:

```
Run github-test/docker-login-action@node-16
::save-state name=isPost::true
##[debug]Save intra-action state isPost = true
::save-state name=registry::***.dkr.ecr.us-west-2.amazonaws.com
##[debug]Save intra-action state registry = ***.dkr.ecr.us-west-2.amazonaws.com
::save-state name=logout::true
##[debug]Save intra-action state logout = true
Retrieving registries data through AWS SDK...
##[debug]Requesting AWS ECR auth token for ***
##[debug]Using http proxy http://proxy-us-aws.xxx.yyy:3128/
##[debug]Using https proxy http://proxy-us-aws.xxx.yyy:3128/
AWS ECR detected with us-west-2 region
Logging into https://***.dkr.ecr.us-west-2.amazonaws.com...
Login Succeeded!
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Login to AWS ECR
```
Thank you,
Milos

**Comment by crazy-max** [comment]
Thanks again!

**Comment by jguillon** [comment]
Hi! 
I ran into the following error message using `act` to run it locally:
```
Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16
```
I guess it's related to this PR, but do I have to change something on my side?

Thanks for your help,
Jeremy

**Comment by crazy-max** [comment]
@jguillon This is not officially supported by GitHub. Suggest to open an issue on the `act` repo: https://github.com/nektos/act/search?q=node16&type=issues

**Comment by jguillon** [comment]
Noted. For those who need to bypass the issue; simply `uses: docker/login-action@v1.13.0`.

**Pull request merged**
