### PR TITLE
 Add Quay.io usage docs

### PR DESCRIPTION
**Pull request by syscll**
Have been using this action successfully with quay.io for a while now, and while the setup is trivial, I thought it would be useful to add some usage docs.

### CODE REVIEW

**Review by crazy-max — CHANGES_REQUESTED** [review]
@syscll Can you update the TOC please?

**Review by crazy-max — APPROVED** [review]
LGTM

**Comment by syscll** [comment]
@crazy-max are you ok to merge?

**Review by mahdiamer — APPROVED** [review]
- [ ]

**Pull request merged**
